services:
  ifx:
    image: icr.io/informix/informix-developer-database:latest
    container_name: ifx
    hostname: ifx
    privileged: true
    environment:
      - LICENSE=accept
    ports:
      - "9088:9088"
      - "9089:9089"
      - "27017:27017"
      - "27018:27018"
      - "27883:27883"
    volumes:
      # Mapea tu carpeta local de backups al contenedor
      - ./backups:/mnt/backup
    stdin_open: true # Equivale al -i
    tty: true        # Equivale al -t

    # Una vez creada la base de datos se tiene que ejecutar en el servidor ontape -s -B <base_de_datos>