/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthconceptsRefundIndexImport } from './routes/_auth/(concepts)/refund/index'
import { Route as AuthconceptsForteIndexImport } from './routes/_auth/(concepts)/forte/index'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthconceptsRefundIndexRoute = AuthconceptsRefundIndexImport.update({
  id: '/(concepts)/refund/',
  path: '/refund/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthconceptsForteIndexRoute = AuthconceptsForteIndexImport.update({
  id: '/(concepts)/forte/',
  path: '/forte/',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(concepts)/forte/': {
      id: '/_auth/(concepts)/forte/'
      path: '/forte'
      fullPath: '/forte'
      preLoaderRoute: typeof AuthconceptsForteIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(concepts)/refund/': {
      id: '/_auth/(concepts)/refund/'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof AuthconceptsRefundIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthconceptsForteIndexRoute: typeof AuthconceptsForteIndexRoute
  AuthconceptsRefundIndexRoute: typeof AuthconceptsRefundIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthconceptsForteIndexRoute: AuthconceptsForteIndexRoute,
  AuthconceptsRefundIndexRoute: AuthconceptsRefundIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/signin': typeof SigninRoute
  '/': typeof AuthIndexRoute
  '/forte': typeof AuthconceptsForteIndexRoute
  '/refund': typeof AuthconceptsRefundIndexRoute
}

export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/': typeof AuthIndexRoute
  '/forte': typeof AuthconceptsForteIndexRoute
  '/refund': typeof AuthconceptsRefundIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/signin': typeof SigninRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/(concepts)/forte/': typeof AuthconceptsForteIndexRoute
  '/_auth/(concepts)/refund/': typeof AuthconceptsRefundIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/signin' | '/' | '/forte' | '/refund'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/' | '/forte' | '/refund'
  id:
    | '__root__'
    | '/_auth'
    | '/signin'
    | '/_auth/'
    | '/_auth/(concepts)/forte/'
    | '/_auth/(concepts)/refund/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SigninRoute: typeof SigninRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SigninRoute: SigninRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/signin"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/",
        "/_auth/(concepts)/forte/",
        "/_auth/(concepts)/refund/"
      ]
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/(concepts)/forte/": {
      "filePath": "_auth/(concepts)/forte/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/(concepts)/refund/": {
      "filePath": "_auth/(concepts)/refund/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
