/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthconceptsRefundIndexRouteImport } from './routes/_auth/(concepts)/refund/index'
import { Route as AuthconceptsForteIndexRouteImport } from './routes/_auth/(concepts)/forte/index'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthconceptsRefundIndexRoute = AuthconceptsRefundIndexRouteImport.update({
  id: '/(concepts)/refund/',
  path: '/refund/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthconceptsForteIndexRoute = AuthconceptsForteIndexRouteImport.update({
  id: '/(concepts)/forte/',
  path: '/forte/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninRoute
  '/': typeof AuthIndexRoute
  '/forte': typeof AuthconceptsForteIndexRoute
  '/refund': typeof AuthconceptsRefundIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/': typeof AuthIndexRoute
  '/forte': typeof AuthconceptsForteIndexRoute
  '/refund': typeof AuthconceptsRefundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/signin': typeof SigninRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/(concepts)/forte/': typeof AuthconceptsForteIndexRoute
  '/_auth/(concepts)/refund/': typeof AuthconceptsRefundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/signin' | '/' | '/forte' | '/refund'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/' | '/forte' | '/refund'
  id:
    | '__root__'
    | '/_auth'
    | '/signin'
    | '/_auth/'
    | '/_auth/(concepts)/forte/'
    | '/_auth/(concepts)/refund/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SigninRoute: typeof SigninRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/(concepts)/refund/': {
      id: '/_auth/(concepts)/refund/'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof AuthconceptsRefundIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/(concepts)/forte/': {
      id: '/_auth/(concepts)/forte/'
      path: '/forte'
      fullPath: '/forte'
      preLoaderRoute: typeof AuthconceptsForteIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthconceptsForteIndexRoute: typeof AuthconceptsForteIndexRoute
  AuthconceptsRefundIndexRoute: typeof AuthconceptsRefundIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthconceptsForteIndexRoute: AuthconceptsForteIndexRoute,
  AuthconceptsRefundIndexRoute: AuthconceptsRefundIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
