/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthKardexIndexRouteImport } from './routes/_auth/kardex/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthconceptsRefundIndexRouteImport } from './routes/_auth/(concepts)/refund/index'
import { Route as AuthconceptsForteIndexRouteImport } from './routes/_auth/(concepts)/forte/index'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKardexIndexRoute = AuthKardexIndexRouteImport.update({
  id: '/kardex/',
  path: '/kardex/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthconceptsRefundIndexRoute = AuthconceptsRefundIndexRouteImport.update({
  id: '/(concepts)/refund/',
  path: '/refund/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthconceptsForteIndexRoute = AuthconceptsForteIndexRouteImport.update({
  id: '/(concepts)/forte/',
  path: '/forte/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/signin': typeof SigninRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kardex/': typeof AuthKardexIndexRoute
  '/forte/': typeof AuthconceptsForteIndexRoute
  '/refund/': typeof AuthconceptsRefundIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kardex': typeof AuthKardexIndexRoute
  '/forte': typeof AuthconceptsForteIndexRoute
  '/refund': typeof AuthconceptsRefundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/signin': typeof SigninRoute
  '/_auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/kardex/': typeof AuthKardexIndexRoute
  '/_auth/(concepts)/forte/': typeof AuthconceptsForteIndexRoute
  '/_auth/(concepts)/refund/': typeof AuthconceptsRefundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/api/auth/$'
    | '/kardex/'
    | '/forte/'
    | '/refund/'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/' | '/api/auth/$' | '/kardex' | '/forte' | '/refund'
  id:
    | '__root__'
    | '/_auth'
    | '/signin'
    | '/_auth/'
    | '/api/auth/$'
    | '/_auth/kardex/'
    | '/_auth/(concepts)/forte/'
    | '/_auth/(concepts)/refund/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kardex/': {
      id: '/_auth/kardex/'
      path: '/kardex'
      fullPath: '/kardex/'
      preLoaderRoute: typeof AuthKardexIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/(concepts)/refund/': {
      id: '/_auth/(concepts)/refund/'
      path: '/refund'
      fullPath: '/refund/'
      preLoaderRoute: typeof AuthconceptsRefundIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/(concepts)/forte/': {
      id: '/_auth/(concepts)/forte/'
      path: '/forte'
      fullPath: '/forte/'
      preLoaderRoute: typeof AuthconceptsForteIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthKardexIndexRoute: typeof AuthKardexIndexRoute
  AuthconceptsForteIndexRoute: typeof AuthconceptsForteIndexRoute
  AuthconceptsRefundIndexRoute: typeof AuthconceptsRefundIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthKardexIndexRoute: AuthKardexIndexRoute,
  AuthconceptsForteIndexRoute: AuthconceptsForteIndexRoute,
  AuthconceptsRefundIndexRoute: AuthconceptsRefundIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
